### ISSUE TITLE
Configure app for dev and production environments (FSND-heavy)

### ISSUE THREAD

**Issue by allanbreyes** [mudacity/udyssey#7]
We have a few options to do this, and I'm open to suggestions.  At this point, it may be easier to deploy to a PaaS like Heroku.  I've also configured it to be friendly with `virtualenv`, so we could also deploy it to an AMI as a mod_wsgi app.  We need to figure out a way to share ENV variables and keys.  Not sure how to do this...

**Comment by DawoonC** [comment]
I guess using vagrant could be an option. Also have no clue about the ENV variables and keys though :)
